Linter rspec admin
trkin/kindergarten-exchange pull request #26
Opened 2023-03-24 05:00 UTC by DeVuDeveloper

Hi,

2023-03-26 17:00 UTC, duleorlovic requested changes

2023-03-28 05:03 UTC, duleorlovic commented on config/environments/development.rb
> +  config.action_mailer.smtp_settings = {
When I run `bin/dev` I receive following error

```
 /Users/dule/kindergarten-exchange/config/environments/development.rb:68:in `fetch': key not found: "SMTP_PORT" (KeyError)
```

Can you remove this block ?

2023-03-28 06:10 UTC, DeVuDeveloper commented
Dobro jutro Dusane, to je odavno ispravljeno. Ta greska je zato sto je
env.example bio prazan. Instalirao sam letter-opener gem za development
umes to a toga. Pokusaj sa git pull, muslim da imas stari kod lokalno.

On Tue, Mar 28, 2023 at 7:03 AM Dusan Orlovic ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In config/environments/development.rb
> <https://github.com/trkin/kindergarten-exchange/pull/26#discussion_r1150030666>
> :
>
> > @@ -62,4 +63,15 @@
>
>    # Uncomment if you wish to allow Action Cable access from any origin.
>    # config.action_cable.disable_request_forgery_protection = true
> +
> +  config.action_mailer.smtp_settings = {
>
> When I run bin/dev I receive following error
>
>  /Users/dule/kindergarten-exchange/config/environments/development.rb:68:in `fetch': key not found: "SMTP_PORT" (KeyError)
>
> Can you remove this block ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/trkin/kindergarten-exchange/pull/26#discussion_r1150030666>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWLERYOPH456TVLUXGAIPP3W6JWLZANCNFSM6AAAAAAWGCX4JM>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-03-28 06:45 UTC, closed without merging

2023-03-28 06:50 UTC, duleorlovic commented
Yeste, u pravu si, lokalno sam imao neku staru granu.