Update README.md
trkin/kindergarten-exchange pull request #35
Opened 2023-03-29 10:16 UTC by itmilos

Add warning for Rails S

2023-03-29 13:32 UTC, DeVuDeveloper requested changes

2023-03-29 13:32 UTC, DeVuDeveloper commented on README.md
### **Hi @itmilos,** 

### **Good job so far!**
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

- You should explain we use bundle install, yarn, bin/setup, and bin/dev for trigger foreman and the app is visible on localhost:3000 in the browser
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

2023-04-06 13:45 UTC, DeVuDeveloper requested changes

2023-04-06 13:45 UTC, DeVuDeveloper commented on README.md
>  ```
I don't understand this. I see you have comments on the issue and if you made the Figma design it is a very nice job.
So please delete this branch and the pull request will go, as we don't need it.

2023-06-06 16:33 UTC, duleorlovic approved these changes

2023-06-06 16:33 UTC, duleorlovic commented on README.md
> +## DO NOT USE STANDARD RAILS S
@itmilos can you use bold instead of header. This is default of new rails apps so it is not so important. Please put below this paragraph, close to the actual `bin/dev` command

2023-06-06 16:33 UTC, merged