[#62] Convert Figma to HTML and Contact form
trkin/kindergarten-exchange pull request #66
Opened 2023-05-12 11:48 UTC by vesnalesevic

2023-05-16 05:06 UTC, duleorlovic requested changes

2023-05-17 09:25 UTC, mankec commented
@duleorlovic Please review.

2023-05-17 11:09 UTC, mankec approved these changes

2023-05-17 11:10 UTC, mankec approved these changes

2023-05-17 11:12 UTC, mankec commented on app/views/devise/registrations/new.html.erb
> +<div class="lg:h-full flex">
@duleorlovic Let's use Devise for now, we can do this in some other issue.

2023-05-17 11:13 UTC, mankec commented on config/routes.rb
> +    authenticated :user do
Removed.

2023-05-17 11:16 UTC, merged