Ability for visitors to create a wish and multiple wish kindergartens
trkin/kindergarten-exchange pull request #82
Opened 2023-05-26 10:27 UTC by vesnalesevic

2023-05-31 10:30 UTC, duleorlovic requested changes

2023-05-31 10:30 UTC, duleorlovic commented on app/javascript/application.js
> +    fetch('/wishes.json')
We do not use json, can you write kindergarten location as data attribute

2023-05-31 10:30 UTC, duleorlovic commented on app/models/user.rb
> +  validate :passwords_match
I thint we do not need this

2023-06-02 11:06 UTC, closed without merging

2023-06-02 11:07 UTC, vesnalesevic commented
This pull request is not valid anymore